# Stage 0, based on Node.js, to build and compile Angular
FROM node:10 as node
WORKDIR /app
COPY package.json /app/
RUN npm install -g @angular/cli@6.0.5
RUN npm install
COPY ./ /app/
ARG env=prod
RUN npm run build -- --prod  --no-aot  --environment $env


FROM  nginx
COPY --from=node /app/dist/ /usr/share/nginx/html
#RUN  rm /etc/nginx/site-available/default
COPY ./nginx-custom.conf /etc/nginx/site-available/default
EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]
